stages:
  - test

podman_in_podman_job:
  stage: test
  image: quay.io/podman/stable:latest
  tags: ["podman"]
  variables:
    FF_NETWORK_PER_BUILD: "false"
  before_script:
    - echo "$CI_JOB_TOKEN" | podman login registry.gitlab.com -u gitlab-ci-token --password-stdin
  script:
    - dnf install -y curl tree  # Install curl and tree
    - mkdir -p ./eib/base-images ./eib/logs ./eib/iso
    - mkdir -p /logs
    - mkdir -p ./containers
    - |
      curl -L --header "PRIVATE-TOKEN: $PRIV_TOKEN" --retry 5 --retry-connrefused --output ./eib/base-images/SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso \
      "https://gitlab.com/api/v4/projects/61162578/packages/generic/suse_enterprise/5.5.0/SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso"
    - ls -asl ./eib/base-images
    - podman info  # Verify Podman information
    - cat /etc/containers/containers.conf  # Verify the configuration content
    - |
      podman run --security-opt label=disable --rm --privileged \
      -v ./containers:/var/lib/containers:rw -v $(pwd)/eib:/eib registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile/suse/edge-image-builder:1.0.2 build --definition-file definition.yaml --config-dir /eib --build-dir /eib/_build || true
      tree ./eib
      # UNCOMMENT FOR DEBUGGING LOG OUTPUT
      # cp ./eib/_build/build*/*.log ./eib/logs/
    - |
      curl -v -H --header "PRIVATE-TOKEN: $PRIV_TOKEN" --upload-file "./eib/clustername-cp.iso" \
      "https://gitlab.com/api/v4/projects/61162578/packages/generic/suse_enterprise/5.5.0/clustername-cp.iso"
  # UNCOMMENT HERE FOR DEBUGGING
  # artifacts:
  #   paths:
  #     - ./eib/logs/*.log
  #   when: always
  #   expire_in: 1 hour
