stages:
  - test

# -------------------------------- CURL ISO -------------------------------- #
# base_iso_curl:
#   stage: test
#   image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/curlimages/curl
#   script:
#     - |
#       curl -L --header "PRIVATE-TOKEN: $PRIV_TOKEN" --retry 5 --retry-connrefused --output SL-Micro-6.0-Packages-x86_64-GM.iso \
#       "https://gitlab.com/api/v4/projects/61162578/packages/generic/suse_enterprise/6.0.0/SL-Micro-6.0-Packages-x86_64-GM.iso"
#     - |
#       file_size=$(stat -c%s SL-Micro-6.0-Packages-x86_64-GM.iso)
#       if [ "$file_size" -lt 1000000000 ]; then
#         echo "Error: The ISO file is smaller than expected (only $file_size bytes)."
#         exit 1
#       fi

#   artifacts:
#     paths:
#       - SL-Micro-6.0-Packages-x86_64-GM.iso.part-*
#     expire_in: 1 hour
podman_in_podman_job:
  stage: test
  image: quay.io/podman/stable:latest
  script:
    # - zypper ref
    # - zypper --non-interactive install -y tree curl crun tar gzip wget podman
    - dnf install -y curl tree  # Install curl and tree
    - mkdir -p ./eib/base-images ./eib/logs ./eib/iso
    - mkdir -p /logs
    - mkdir -p ./containers
    - |
      curl -L --header "PRIVATE-TOKEN: $PRIV_TOKEN" --retry 5 --retry-connrefused --output SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso \
      "https://gitlab.com/api/v4/projects/61162578/packages/generic/suse_enterprise/6.0.0/SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso"
    - cp SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso ./eib/base-images
    - ls -asl ./eib/base-images
    - podman info  # Verify Podman information
    - |
      PODMAN_LOG_LEVEL=debug podman run --security-opt label=disable --rm --privileged --net=host \
      -v ./containers:/var/lib/containers:rw -v $(pwd)/eib:/eib registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile/suse/edge-image-builder:1.0.2 build --definition-file definition.yaml --config-dir /eib --build-dir /eib/_build || true
      tree ./eib
      cp ./eib/_build/build*/*.log ./eib/logs/
  artifacts:
    paths:
      - ./eib/logs/*.log
    when: always
    expire_in: 1 hour
