stages:
  - build_iso

# Define global variables that can be overridden for different jobs
variables:
  BASE_FOLDER: "site/shop"  # Default base folder path
  IMAGE_VERSION: "1.0.2"  # Default Edge Image Builder version
  CUSTOM_OUTPUT_IMAGE_NAME: "custom_output.iso"  # Default output image name
  OUTPUT_IMAGE_NAME: "SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso"  # Default output image name

# Template job for building ISOs
.build_iso_template:
  stage: build_iso
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10
  services:
    - docker:20.10-dind
  variables:
    FF_NETWORK_PER_BUILD: "false"
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login registry.gitlab.com -u gitlab-ci-token --password-stdin
  script:
    - apk add --no-cache curl tree
    - mkdir -p $(pwd)/eib/base-images $(pwd)/eib/logs $(pwd)/eib/iso $(pwd)/containers /logs
    - mkdir -p /logs
    - cp -r ${BASE_FOLDER}/* $(pwd)/eib/
    - echo "Starting CURL OUTPUT" >> ./eib/logs/script.log
    - find ./eib/ -type f -exec sed -i "s/OUTPUT_IMAGE_NAME/${OUTPUT_IMAGE_NAME}/g" {} +
    - find ./eib/ -type f -exec sed -i "s/BASE_IMAGE_NAME/${BASE_IMAGE_NAME}/g" {} +
    - |
      curl -L --header "PRIVATE-TOKEN: $PRIV_TOKEN" --retry 5 --retry-connrefused --output $(pwd)/eib/base-images/${OUTPUT_IMAGE_NAME} \
      "https://gitlab.com/api/v4/projects/61162578/packages/generic/suse_enterprise/5.5.0/${OUTPUT_IMAGE_NAME}"
    - ls -asl $(pwd)/eib/base-images
    - docker info
    - |
      docker run --rm --privileged \
      -v $(pwd)/containers:/var/lib/containers:rw -v $(pwd)/eib:/eib registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile/suse/edge-image-builder:${IMAGE_VERSION} build --definition-file /eib/definition.yaml --config-dir /eib --build-dir /eib/_build || true
    - tree $(pwd)/eib
    - cp $(pwd)/eib/_build/build*/*.log $(pwd)/eib/logs/
    - |
      curl -v --retry 5 --retry-delay 10 -H "PRIVATE-TOKEN: $PRIV_TOKEN" --upload-file "$(pwd)/eib/${OUTPUT_IMAGE_NAME}" \
      "https://gitlab.com/api/v4/projects/61162578/packages/generic/suse_enterprise/5.5.0/${CUSTOM_OUTPUT_IMAGE_NAME}-$CI_COMMIT_SHORT_SHA.iso" || true
  artifacts:
    paths:
      - $(pwd)/eib/logs/*.log
    when: always
    expire_in: 1 hour

# Job for building ISO for Site/Shop1
build_iso_site_shop1:
  extends: .build_iso_template
  variables:
    BASE_FOLDER: "site/shop1"  # Override the base folder path for this job
    IMAGE_VERSION: "1.0.2"  # Specify the Edge Image Builder version
    OUTPUT_IMAGE_NAME: "shop1_output.iso" 
    OUTPUT_IMAGE_NAME: "SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso" 

# Job for building ISO for Site/Shop2
build_iso_site_shop2:
  extends: .build_iso_template
  variables:
    BASE_FOLDER: "site/shop2"  # Override the base folder path for this job
    IMAGE_VERSION: "1.0.1"  # Use a different version of the Edge Image Builder
    OUTPUT_IMAGE_NAME: "shop2_output.iso"
    OUTPUT_IMAGE_NAME: "SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso" 

# stages:
#   - build_iso

# docker_in_docker_job_with_docker_runner:
#   stage: build_iso
#   image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10  # Using Docker image for Docker-in-Docker
#   services:
#     - docker:20.10-dind  # Service for Docker Daemon in Docker
#   variables:
#     FF_NETWORK_PER_BUILD: "false"
#     DOCKER_DRIVER: overlay2
#     DOCKER_TLS_CERTDIR: ""  # Disable TLS to simplify the connection
#     DOCKER_HOST: tcp://docker:2375  # Use the Docker service alias
#   before_script:
#     - echo "$CI_JOB_TOKEN" | docker login registry.gitlab.com -u gitlab-ci-token --password-stdin
#   script:
#     - apk add --no-cache curl tree  # Install curl and tree for Alpine-based Docker image
#     - mkdir -p $(pwd)/eib/base-images $(pwd)/eib/logs $(pwd)/eib/iso $(pwd)/containers /logs
#     - mkdir -p /logs
#     - echo "Starting CURL OUTPUT" >> ./eib/logs/script.log
#     - |
#       curl -L --header "PRIVATE-TOKEN: $PRIV_TOKEN" --retry 5 --retry-connrefused --output $(pwd)/eib/base-images/SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso \
#       "https://gitlab.com/api/v4/projects/61162578/packages/generic/suse_enterprise/5.5.0/SLE-Micro.x86_64-5.5.0-Default-RT-SelfInstall-GM2.install.iso"
#     - ls -asl $(pwd)/eib/base-images
#     - docker info  # Verify Docker information
#     - |
#       docker run --rm --privileged \
#       -v $(pwd)/containers:/var/lib/containers:rw -v $(pwd)/eib:/eib registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile/suse/edge-image-builder:1.0.2 build --definition-file definition.yaml --config-dir /eib --build-dir /eib/_build || true
#       tree $(pwd)/eib
#       cp $(pwd)/eib/_build/build*/*.log $(pwd)/eib/logs/
#       #find ./eib -type f -name "*.log" -exec cp {} $(pwd)/eib/logs/ \;
#     - |
#       curl -v --retry 5 --retry-delay 10 -H "PRIVATE-TOKEN: $PRIV_TOKEN" --upload-file "$(pwd)/eib/clustername-cp.iso" \
#       "https://gitlab.com/api/v4/projects/61162578/packages/generic/suse_enterprise/5.5.0/clustername-cp-$CI_COMMIT_SHORT_SHA.iso" || true
#   artifacts:
#     paths:
#       - $(pwd)/eib/logs/*.log
#     when: always
#     expire_in: 1 hour

