stages:
  - test

# -------------------------------- CURL ISO -------------------------------- #
base_iso_curl:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/curlimages/curl
  script:
  - |
    curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --output SL-Micro-6.0-Packages-x86_64-GM.iso \
    "https://gitlab.com/api/v4/projects/61162578/packages/generic/suse_enterprise/6.0.0/SL-Micro-6.0-Packages-x86_64-GM.iso"
  artifacts:
    paths:
      - SL-Micro-6.0-Packages-x86_64-GM.iso
    expire_in: 1 hour

podman_job:
  stage: test
  image: opensuse/tumbleweed
  needs:
    - base_iso_curl
  script:
    - zypper ref
    - zypper --non-interactive install -y podman runc tree docker
    - ls -asl | grep *.iso
    - mkdir -p ./eib/base-images ./eib/logs ./eib/iso
    - cp SL-Micro-6.0-Packages-x86_64-GM.iso ./eib/base-images
    - podman info  # Verify Podman info
    - |
      podman run --rm --privileged -v $(pwd)/eib:/eib registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile/suse/edge-image-builder:1.0.1 build --definition-file definition.yaml || true
      tree ./eib
      cp ./eib/_build/build*/*.log ./eib/logs/
      cp ./eib/_build/build*/iso-extract/*.iso ./eib/iso/
  artifacts:
    paths:
      - SL-Micro-6.0-Packages-x86_64-GM.iso
      - ./eib/logs/*.log
      - ./eib/iso/*.iso
    when: always
    expire_in: 1 hour
