stages:
  - test

# -------------------------------- CURL ISO -------------------------------- #
base_iso_curl:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/curlimages/curl
  script:
  - |
    curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --output SLE-Micro.x86_64-5.5.0-Default-SelfInstall-Build9.2.install.iso \
    "https://gitlab.goriv.co/api/v4/projects/it/etmi/mcp/baremetal-image-builder/packages/generic/iso/5.5.0/install.iso"
    curl go.uber.org
  artifacts:
    paths:
      - SLE-Micro.x86_64-5.5.0-Default-SelfInstall-Build9.2.install.iso
    expire_in: 1 hour

podman_job:
  stage: test
  image: opensuse/tumbleweed
  needs:
    - base_iso_curl
  script:
    - zypper ref
    - zypper install -y podman
    - podman run --rm --privileged -it -v .:/eib registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile/suse/edge-image-builder:1.0.1 build --definition-file ./definition.yaml
  artifacts:
    paths:
      - SLE-Micro.x86_64-5.5.0-Default-SelfInstall-Build9.2.install.iso
    expire_in: 1 hour
    

    #https://gitlab.com/sre-baremetal/EIBer/-/package_files/145086370/download
    # - podman info
    # - podman run --rm docker.io/library/alpine:latest echo "Podman is working!"
